version: '3.6'
services:
  es01:
    image: elasticsearch:7.2.0
    container_name: elastic01
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    secrets:
      - source: elasticsearch.compose
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - elk-net

  es02:
    image: elasticsearch:7.2.0
    container_name: elastic02
    environment:
      - node.name=es02
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    secrets:
      - source: elasticsearch.compose
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - elk-net

  es03:
    image: elasticsearch:7.2.0
    container_name: elastic03
    environment:
      - node.name=es03
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    secrets:
      - source: elasticsearch.compose
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - elk-net


  kibana:
    image: kibana:7.2.0
    container_name: kibana01
    environment:
      - SERVER_HOST=0.0.0.0
    volumes:
      - ./kibana.compose:/usr/share/kibana/config/kibana.yml:rw
    ports:
      - 5601:5601
    networks:
      - elk-net
    depends_on: ['es03']


networks:
 elk-net:  

secrets:
  elasticsearch.compose:
    file: /root/elastic/elasticsearch.compose
