FROM centos:centos7.7.1908
yum update -y
yum install -y yum-utils device-mapper-persistent-data lvm2 vim
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install docker-ce docker-ce-cli containerd.io
yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
