FROM centos:centos7.7.1908
COPY kubernetes.repo /etc/yum.repos.d/
RUN yum update -y
RUN yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
RUN yum install -y yum-utils device-mapper-persistent-data lvm2 vim docker-ce docker-ce-cli containerd.io kubelet kubeadm kubectl bash-completion 

